foreground              #d8dee9
background              #0f1115
background_opacity      1.0
cursor                  #cfd6e6

selection_foreground    #000000
selection_background    #c7c7c7

active_tab_foreground   #ffffff
active_tab_background   #1c1c1c
inactive_tab_foreground #bfbfbf
inactive_tab_background #000000

active_border_color     #3a3a3a
inactive_border_color   #1a1a1a
bell_border_color       #ff5f5f


# ===== NORMAL COLORS =====
color0   #000000
color1   #ff5f5f  
color2   #5fd787  
color3   #ffaf00  
color4   #5f87ff  
color5   #af5fff  
color6   #00d7af  
color7   #d7d7d7

# ===== BRIGHT COLORS =====
color8   #262626
color9   #ff8787
color10  #87ffaf
color11  #ffd75f
color12  #87afff
color13  #d787ff
color14  #5fffff
color15  #ffffff
