font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font
font_size 10.8

disable_ligatures always

cursor_shape block
shell_integration no-cursor

window_padding_width 6
confirm_os_window_close 0

map ctrl+shift+alt+super+f12 show_active_gpu_info

include colors.conf
