set errorbells
set mouse+=a
set autowriteall
set ignorecase
set smartcase
set completeopt=menuone,noselect
set guicursor=
set updatetime=300
set nobackup
set nowritebackup
set hidden
set termguicolors
set signcolumn=no
set shortmess+=c
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nu
set nowrap
set scrolloff=8
set relativenumber
set noswapfile
set incsearch
set encoding=utf-8
set nohlsearch
set cmdheight=2
